name: Lean 4 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v3

    # Clear cache to ensure fresh Lean installation
    - name: Clear Lean cache
      run: rm -rf $HOME/.elan

    # Install Lean 4 and Lake with the specified version
    - name: Install Lean 4 and Lake
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.3.0
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        lake --version || (curl https://raw.githubusercontent.com/leanprover/lake/master/lake-install.sh -sSf | sh -s --)

    # Update dependencies (including mathlib)
    - name: Update Lake dependencies
      run: lake update

    # Build the project
    - name: Build project
      run: lake build
